### ISSUE TITLE
I get an Error Beacuse of  Date.getUnixTime()

### ISSUE THREAD

**Issue by vadimchilinciuc** [ranjandsingh/sharp-multer#3]
I get an Error Beacuse of  Date.getUnixTime()

const getFilename = (name, input) =>
  name.split(".").slice(0, -1).join(".") +
  `${input.useTimestamp ? "-" +  Date.getUnixTime() : ""}` +
  "." +
  input.fileFormat;
  
  PROPOSE: Date.now() :
  
const getFilename = (name, input) =>
  name.split(".").slice(0, -1).join(".") +
  `${input.useTimestamp ? "-" + Date.now() : ""}` +
  "." +
  input.fileFormat;

**Comment by ranjandsingh** [comment]
hey can provide context or Env you are working in Thanks.

**Comment by ranjandsingh** [comment]
@vadimchilinciuc

**Comment by vadimchilinciuc** [comment]
yes i work on a node application , and the error is :
(node:35230) UnhandledPromiseRejectionWarning: TypeError: Date.getUnixTime is not a function
    at getFilename (/home/vadim/git/backend/node_modules/sharp-multer/index.js:10:38)
    at handleSave (/home/vadim/git/backend/node_modules/sharp-multer/index.js:91:18)
    at /home/vadim/git/backend/node_modules/sharp-multer/index.js:122:5
    at MyCustomStorage.destination [as getDestination] (/home/vadim/git/backend/src/controller.ts:43:43)
    at MyCustomStorage._handleFile (/home/vadim/git/backend/node_modules/sharp-multer/index.js:120:8)
    at /home/vadim/git/backend/node_modules/multer/lib/make-middleware.js:137:17
    at multerFilter (/home/vadim/git/backend/src/controller.ts:36:9)
    at wrappedFileFilter (/home/vadim/git/backend/node_modules/multer/index.js:44:7)
    at Multipart.<anonymous> (/home/vadim/git/backend/node_modules/multer/lib/make-middleware.js:107:7)
    at Multipart.emit (events.js:400:28)
    at HeaderParser.cb (/home/vadim/git/backend/node_modules/busboy/lib/types/multipart.js:358:14)
    at HeaderParser.push (/home/vadim/git/backend/node_modules/busboy/lib/types/multipart.js:162:20)
    at SBMH.ssCb [as _cb] (/home/vadim/git/backend/node_modules/busboy/lib/types/multipart.js:394:37)
    at feed (/home/vadim/git/backend/node_modules/streamsearch/lib/sbmh.js:248:10)
    at SBMH.push (/home/vadim/git/backend/node_modules/streamsearch/lib/sbmh.js:104:16)
    at Multipart._write (/home/vadim/git/backend/node_modules/busboy/lib/types/multipart.js:567:19)
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by vadimchilinciuc** [comment]
node v:v14.19.3

**Comment by ranjandsingh** [comment]
Thanks your patch is deployed already 👍

**Comment by vadimchilinciuc** [comment]
Thanks to you dear !
